import { store } from '../store'

function triggerBlobDownload(blob, filename) {
  const objectUrl = URL.createObjectURL(blob)
  const a = document.createElement('a')
  a.href = objectUrl
  a.download = filename
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(objectUrl)
}

async function extractErrorMessage(res, fallback) {
  try {
    const json = await res.json()
    return json?.message || fallback
  } catch {
    return fallback
  }
}

/**
 * Fetch a binary file (PDF/xlsx) from an authenticated GET endpoint as a Blob — the shared
 * primitive behind both downloading a file and previewing one inline (e.g. in an <iframe>).
 */
export async function fetchFileBlob(path) {
  const token = store.getState().auth.accessToken
  const baseUrl = import.meta.env.VITE_API_URL || '/api'

  const res = await fetch(`${baseUrl}${path}`, {
    method: 'GET',
    headers: { Authorization: token ? `Bearer ${token}` : '' },
    credentials: 'include',
  })

  if (!res.ok) throw new Error(await extractErrorMessage(res, 'Failed to load file'))
  return res.blob()
}

/**
 * Download a binary file (PDF/xlsx) from an authenticated GET endpoint.
 * Raw fetch (not RTK Query) since the response is a blob, not JSON.
 */
export async function downloadFileGet(path, filename) {
  triggerBlobDownload(await fetchFileBlob(path), filename)
}

/**
 * Download a binary file (PDF/xlsx) generated by an authenticated POST endpoint.
 */
export async function downloadFilePost(path, body, filename) {
  const token = store.getState().auth.accessToken
  const baseUrl = import.meta.env.VITE_API_URL || '/api'

  const res = await fetch(`${baseUrl}${path}`, {
    method: 'POST',
    headers: {
      Authorization: token ? `Bearer ${token}` : '',
      'Content-Type': 'application/json',
    },
    credentials: 'include',
    body: JSON.stringify(body),
  })

  if (!res.ok) throw new Error(await extractErrorMessage(res, 'Failed to generate file'))
  triggerBlobDownload(await res.blob(), filename)
}
